### ISSUE TITLE
This has started spamming my blog

### ISSUE THREAD

**Issue by edent** [snarfed/hackermention#1]
Love the idea of this project - but it has suddenly sent me over 20 comments to an ancient blog post:

![Screenshot of lots of comments](https://user-images.githubusercontent.com/837136/185742679-a55ab067-06de-4ef0-97bc-53263085434a.png)

Perhaps consider making this opt-in? Or only for new stories?

**Comment by snarfed** [comment]
Sorry for the trouble! We discussed this on #indieweb-dev a bit just now. I can definitely turn this off for your site, or something similar.

Out of curiosity, is the age the most unwelcome part? Or that you didn't opt in? Or that they're not on topic enough?

We're considering sending just one wm, for the submission page, instead of one per comment. Would you be more or less interested in that?

**Comment by edent** [comment]
Heya,
I think it is three things.

1. I didn't opt in. With Bridgy, I had to deliberately set it up to get webmentions from Twitter & Mastodon. 
2. My blog is on HN *a lot*. I'm not sure I want to cope with 1,000s of comments flooding in.
3. The comments aren't threaded. So even if I accepted them all, it would be impossible to follow the conversation. (This is also a problem with Bridgy)

At the moment, I "fake" a webmention from HN by using a Tweet which mentions it.

I think what I'd personally prefer is receiving a WM say 24 hours after submission which says "Mentioned on HN. 123 points. 45 comments".  Does that make sense?

**Comment by snarfed** [comment]
Thanks for the details! A few thoughts:

> 1. I didn't opt in. With Bridgy, I had to deliberately set it up to get webmentions from Twitter & Mastodon.

True! I'm deliberately pushing the envelope a bit here. Even for sites like HN that don't send webmentions themselves, anyone can send them with just an HTTP POST. And the internet is the wild west, anything that can happen will happen. I'm admittedly trying to demonstrate that early here, so we can think about it while the community is still small and friendly.

Still though, I can definitely back off some here.

> 2. My blog is on HN _a lot_. I'm not sure I want to cope with 1,000s of comments flooding in.

Definitely! Understood.

> 3. The comments aren't threaded. So even if I accepted them all, it would be impossible to follow the conversation. (This is also a problem with Bridgy)

Hmm! They actually are threaded on the source mf2 side, I'm careful to include `in-reply-to` to the parent comment (if any) as well as the original post. Bridgy does this too, eg with Twitter, and I've seen sites that use it to reconstruct the threading, I think even in WordPress. May need the _threaded (nested) comments_ setting enabled on `/wp-admin/options-discussion.php`.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/778068/185761920-1ddb5c6e-a9fe-4acb-a47c-d2c46041e3c8.png">

Regardless, I absolutely hear you, and #indieweb-dev agrees. I'm planning to revise this to only send one webmention per post, not per comment.

**Comment by edent** [comment]
1. Appreciated :-) 
2. :+1: 
3. Interesting. I have threaded comments on https://shkspr.mobi/blog/ - but the Tweet replies don't seem to be threaded.
![Screenshot 2022-08-20 at 20-19-26 Edit Comment ‹ Terence Eden’s Blog — WordPress](https://user-images.githubusercontent.com/837136/185763027-37f0aa74-7f4b-4dc6-b74e-4cef16abd5df.png)

No idea which of my many plugins aren't playing right.
